modLoader = "javafml"
loaderVersion = "[44,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "maxilib"
version = "${file.jarVersion}"
displayName = "MaxiLib"
credits="Credits are on mod's page."
authors="Max094_Reikeb"
description = '''
MaxiLib is a custom mod library for Max's mods
'''

[[dependencies.maxilib]] #optional
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.maxilib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
